<?php

function sortd_toolbar() {
    $items = [];

    $items['SORTD'] = [
        '#cache' => [
            'contexts' => ['user.permissions'],
        ],
    ];

    if (!\Drupal::currentUser()->hasPermission('Access the Commande overview page')) {
        return $items;
    }


    $items['SORTD'] += [
        '#type' => 'toolbar_item',
        '#weight' => 1,
        'tab' => [
            '#type' => 'link',
            '#title' => 'SORTD',
            '#url' => \Drupal\Core\Url::fromUri("internal:/admin/sortd"),
            '#attributes' => [
                'title' => 'sortd menu',
                'class' => ['toolbar-icon', 'toolbar-icon-sortd'],
            ],
        ],
        'tray' => [

            'configuration' => [
                '#type' => 'link',
                '#title' => 'Dashboard',
                '#url' => \Drupal\Core\Url::fromUri("internal:/dashboard"),

            ],[
                '#type' => 'link',
                '#title' => 'Notifications',
                '#url' => \Drupal\Core\Url::fromUri("internal:/apiAuth"),
            ],[
                '#type' => 'link',
                '#title' => 'Settings',
                '#url' => \Drupal\Core\Url::fromUri("internal:/settings"),
            ],[
                '#type' => 'link',
                '#title' => 'Help',
                '#url' => \Drupal\Core\Url::fromUri("internal:/help"),
            ],

        ],
        '#attached' => array(
            'library' => array(
                'sortd/admin',
            ),
        ),

    ];
    return $items;
}


function sortd_theme($existing, $type, $theme, $path) {
    return [
        'settings' => [
            'variables' => ['test_var' => NULL],
        ],
        'get_help' => [
            'variables' => [
                'api_response' => NULL,
            ],
        ],
    ];
}
